### ISSUE TITLE
Custom fonts not working when building

### ISSUE THREAD

**Issue by seanenriquez** [alexnoz/webpack-pug-scss-boilerplate#27] opened 2020-12-20 05:03 UTC
I've tried starting from a completely clean repo and have a font in every possible format the loader supports. Can't get a single font to show up in the page's source when building.

I've noticed system fonts will work, which kind of gives the impression that some fonts work, but i believe something is wrong.

**Comment by alexnoz** [comment] 2020-12-20 12:21
Can you provide the exact steps to reproduce the issue, or even better, a repo? I can't reproduce it, what I did:
1. pull a fresh new repo
2. put `woff2` file into `app/fonts`
3. put `@font-face` rule in `app/styles/_font.scss` that references the aforementioned font file
4. change `font-family` in `app/styles/main.scss` to the one in the `@font-face` rule

The result works well both in dev & prod modes.

**Comment by seanenriquez** [comment] 2020-12-21 00:08
Well i fixed it working in prod by updating node-sass to 4.12 and when building I just have to drag the font folder into `/styles`

**Comment by alexnoz** [comment] 2020-12-21 19:03
Yeah, `node-sass` is a common source of issues, but it shouldn't affect anything is this case, also everything should work without moving `fonts` anywhere. Ok, I'm closing this for now, feel free to reopen if the issue pops up again.

**Closed as completed by alexnoz** 2020-12-21 19:03 UTC
